### ISSUE TITLE
Run Python 3.5 on Travis

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-python#2350]
@tseaver Maybe I'm crazy? Maybe we shouldn't do this? [Currently](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/6fb2d73ff6350590aa061bcd902422828340f337/.travis.yml#L9-L10) only 2.7 and 3.4 are tested

**Comment by dhermes** [comment]
FWIW we could remove 2.7 since all those are included in `tox -e cover`

**Comment by tseaver** [comment]
Maybe in conjunction with #2070?

**Comment by jonparrott** [comment]
We should do this. The Python runtime for GAE flex is about to update to 3.5

I'd recommend just adding this to `travis.yaml`, as it's simpler than trying to coax your current setup into a matrix:

```yaml
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.5
```
