### ISSUE TITLE
Google App Engine Python 3 Default Version

### ISSUE THREAD

**Issue by pmart123** [GoogleCloudPlatform/google-cloud-python#2910]
I am trying to launch an initial demo app using a private repository on Google App Engine. I have set my Python environment in my yaml config to:

```yaml
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
threadsafe: true

runtime_config:
  python_version: 3
```
When I run:

```bash
gcloud app deploy
```
I notice the build is Python 3.4 on the remote server, and my application errors out when it encounters Python 3.5 only syntax:

```Python
yield {**person, **{'common_name': common_name}}
```

The documentation says the default Python 3 environment should be 3.5.2. Is there any setting that might be causing the build to use 3.4 instead?
