### ISSUE TITLE
storage access not working from within docker within gitlab CI - from google.cloud import storage - ImportError: No module named 'google'

### ISSUE THREAD

**Issue by exjohn** [GoogleCloudPlatform/google-cloud-python#5296]
I have a very similar problem to  #4683. The fixes suggested there didn't work, though. The one difference is that I'm having the docker be built by gitlab CI.

This is my dockerfile:
```
FROM python:3.5.4

WORKDIR /PoC
ADD requirements.txt /PoC/
ADD *.py /PoC/
ADD *.json /PoC/

RUN python3 -m pip install --trusted-host pypi.python.org -r /PoC/requirements.txt

RUN apt-get update && apt-get install -y sudo vim
RUN sudo echo deb http://ftp.uk.debian.org/debian jessie-backports main >>/etc/apt/sources.list
RUN apt-get update && apt-get install -y ffmpeg
RUN mkdir /PoC/resources

CMD python3 server.py --port 4000

ENV GOOGLE_APPLICATION_CREDENTIALS /PoC/api-key.json
ENV PYCURL_SSL_LIBRARY=openssl
```

And this is my .gitlab-ci.yml:
```
stages:
  - build-docker
  - test-docker

build:
  stage: build-docker
  image: docker:latest
  tags:
    - docker
  script:
    - echo "Build base image"
    - docker login ${CI_REGISTRY} -u gitlab-ci-token -p $CI_JOB_TOKEN
    - docker build -t ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME} .
    - docker push ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}
    # - docker run --rm -i ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME} python3 test_analyze_sb.py
    - docker rmi ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}
  except:
    - tags

test:
  stage: test-docker
  image: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}
  script:
    - python3 test_analyze_sb.py
```

See the commented line in the 'build' job? If I run that line, the job passes.

The 'test' job, however, fails and throws:
```
[...]/combined_into_gl_kws.py", line 12, in <module>
    from google.cloud import storage
ImportError: No module named 'google'
```

Any help is very much appreciated!!!
